# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='CreatedAt',
        ),
    ]
