# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_auto_20171227_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='restaurantapi.Category'),
        ),
    ]
