# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0003_auto_20171227_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
    ]
